---
title: "R Notebook"
output: html_notebook
---

# Análisis de hechos delictivos
```{r}
library(dplyr) # Para manejar y manipular datos con %>%
library(arules) # Para uso de algoritmos
library(readxl) # Para lectura de archivo en formato excel
```


## Obtención de datos
```{r}

dAgraviados_2020 <- read_xlsx("Data\\Agraviados 2020.xlsx",sheet = "Sheet1")
dAgraviados_2022 <- read_xlsx("Data\\Agraviados 2022.xlsx", sheet = "Sheet1")


dAgraviados_2023 <- read_xlsx("Data\\Agraviados 2023.xlsx", sheet = "Sheet1")

dSindicados_2023 <- read_xlsx("Data\\Sindicados 2023.xlsx", sheet = "Sheet1")


```

## Obtención de diccionarios
```{r}
dicAgraviados22 <- read_xlsx("Data\\Diccionario 2022.xlsx", sheet="Dic")
dicAgraviados23 <- read_xlsx("Data\\Diccionario Agraviados 2023.xlsx", sheet="Dic")
dicSindicados23 <- read_xlsx("Data\\Diccionario Sindicados 2023.xlsx", sheet="Dic")
```

## Algoritmo Apriori

### Agraviados 2020
```{r}
# Preparación del data set
sdAgraviados20 <- dAgraviados_2020
sdAgraviados20 <- sdAgraviados20[, !(colnames(sdAgraviados20) %in% c("año_denuncia"))]

# Ejecución apriori en datos completos
rAgraviados20 <- apriori(sdAgraviados20, parameter= list(support=0.2, confidence=0.5))

```
```{r}
# Exploración de reglas
inspect(rAgraviados20[0:100])
```

### Agraviados 2022
```{r}
# Preparación del data set
sdAgraviados22 <- dAgraviados_2022
sdAgraviados22 <- sdAgraviados22[, !(colnames(sdAgraviados22) %in% c("año_denuncia"))]

sdAgraviados22 <- sdAgraviados22 %>%
  select(-g_edad_60ymás, -g_edad_80ymás) %>%
  left_join(dicAgraviados22, by = c("delito_com"="Etiqueta")) %>%
  select(-delito_com, -Valor) %>%
  rename(delito_com = Código) %>%
  left_join(dicAgraviados22[dicAgraviados22$Valor == "DEPARTAMENTO DE OCURRENCIA",], by = c("depto_ocu_hecho" ="Etiqueta")) %>%
  select(-depto_ocu_hecho, -Valor) %>%
  rename(depto_ocu_hecho = Código) %>%
  mutate(depto_ocu_hecho = ifelse(depto_ocu_hecho == 2202, 2, depto_ocu_hecho))
  
# Ejecución apriori en datos completos
rAgraviados22 <- apriori(sdAgraviados22, parameter= list(support=0.2, confidence=0.5))

muestra <- as(rAgraviados22,"data.frame")
```

### Exploración de reglas
```{r}
#117	{delito_com=[57,227)} => 
#{sexo_agraviados=Hombre}	0.2125382	0.5696120	0.3731281	1.210362
# Tomando esta regla como punto de partida, se revisan los casos que aplican para este análisis y posteriomente se realia un análisis sobre estos.

# Preparación del data set
sdAgraviados22 <- dAgraviados_2022
sdAgraviados22 <- sdAgraviados22[, !(colnames(sdAgraviados22) %in% c("año_denuncia"))]

sdAgraviados22 <- sdAgraviados22 %>%
  select(-g_edad_60ymás, -g_edad_80ymás) %>%
  left_join(dicAgraviados22, by = c("delito_com"="Etiqueta")) %>%
  select(-delito_com, -Valor) %>%
  rename(delito_com = Código) %>%
  filter(delito_com>=178 & delito_com<=182)  %>%
  left_join(dicAgraviados22[dicAgraviados22$Valor == "DEPARTAMENTO DE OCURRENCIA",], by = c("depto_ocu_hecho" ="Etiqueta")) %>%
  select(-depto_ocu_hecho, -Valor) %>%
  rename(depto_ocu_hecho = Código) %>%
  mutate(depto_ocu_hecho = ifelse(depto_ocu_hecho == 2202, 2, depto_ocu_hecho)) %>%
  left_join(dicAgraviados22, by=c("sexo_agraviados" = "Etiqueta")) %>%
  select(-sexo_agraviados, -Valor) %>%
  rename(sexo_agraviados= Código) %>%
  left_join(dicAgraviados22, by=c("est_conyugal" = "Etiqueta")) %>%
  select(-est_conyugal, -Valor) %>%
  rename(est_conyugal= Código)
  
  
# Ejecución apriori en datos completos
rAgraviados22 <- apriori(sdAgraviados22, parameter= list(support=0.2, confidence=0.5))

muestra <- as(rAgraviados22,"data.frame")


```

### Agraviados 2023
```{r}
# Preparación del data set
sdAgraviados23 <- dAgraviados_2023
sdAgraviados23 <- sdAgraviados23[, !(colnames(sdAgraviados23) %in% c("año_denuncia"))]

sdAgraviados22 <- sdAgraviados22 %>%
  select(-g_edad_60ymás, -g_edad_80ymás) %>%
  left_join(dicAgraviados22, by = c("delito_com"="Etiqueta")) %>%
  select(-delito_com, -Valor) %>%
  rename(delito_com = Código) %>%
  filter(delito_com>=178 & delito_com<=182)  %>%
  left_join(dicAgraviados22[dicAgraviados22$Valor == "DEPARTAMENTO DE OCURRENCIA",], by = c("depto_ocu_hecho" ="Etiqueta")) %>%
  select(-depto_ocu_hecho, -Valor) %>%
  rename(depto_ocu_hecho = Código) %>%
  mutate(depto_ocu_hecho = ifelse(depto_ocu_hecho == 2202, 2, depto_ocu_hecho)) %>%
  left_join(dicAgraviados22, by=c("sexo_agraviados" = "Etiqueta")) %>%
  select(-sexo_agraviados, -Valor) %>%
  rename(sexo_agraviados= Código) %>%
  left_join(dicAgraviados22, by=c("est_conyugal" = "Etiqueta")) %>%
  select(-est_conyugal, -Valor) %>%
  rename(est_conyugal= Código)
  
  
# Ejecución apriori en datos completos
rAgraviados23 <- apriori(sdAgraviados23, parameter= list(support=0.2, confidence=0.5))

muestra23 <- as(rAgraviados23,"data.frame")
```

### Sindicados 2023
```{r}
# Preparación del data set
sdSindicados23 <- dSindicados_2023
sdSindicados23 <- sdSindicados23[, !(colnames(sdSindicados23) %in% c("año_denuncia"))]

sdSindicados23 <- sdSindicados23 %>%
  select(-g_edad_60ymás, -g_edad_80ymás,-g_hora_denuncia_mañ.tar.noch, -g_hora_denuncia,-día_denuncia,-zona_ocu_hecho, -núm_corre) %>%
  left_join(dicSindicados23, by = c("delito_com"="Etiqueta")) %>%
  select(-delito_com, -Valor) %>%
  rename(delito_com = Código) %>%
  #filter(est_conyugal != -99) %>%
  #filter(zona_ocu_hecho != -99) %>%
  mutate(año_hecho = año_hecho - 2000) %>%
  filter(delito_com>= 227) %>%
  filter(delito_com<=231) %>%
  filter(sexo_per != -99) %>%
  filter(edad_sind != -99) %>%
  left_join(dicSindicados23[dicSindicados23$Valor == "DEPARTAMENTO DE OCURRENCIA DEL HECHO",], by = c("depto_ocu_hecho" ="Etiqueta")) %>%
  select(-depto_ocu_hecho, -Valor) %>%
  rename(depto_ocu_hecho = Código) 
  
  
# Ejecución apriori en datos completos
rSindicados23 <- apriori(sdSindicados23, parameter= list(support=0.2, confidence=0.5))

dfReglasSindicados23 <- as(rSindicados23,"data.frame")
```
### Comparación reglas Agraviados 2023
```{r}
# Preparación del data set
sdAgraviados23 <- dAgraviados_2023
sdAgraviados23 <- sdAgraviados23[, !(colnames(sdAgraviados23) %in% c("año_denuncia"))]

sdAgraviados23 <- sdAgraviados23 %>%
  select(-g_edad_60ymás, -g_edad_80ymás,-g_hora_denuncia_mañ.tar.noch, -g_hora_denuncia,-día_denuncia,-zona_ocu_hecho, -núm_corre) %>%
  left_join(dicAgraviados23, by = c("delito_com"="Etiqueta")) %>%
  select(-delito_com, -Valor) %>%
  rename(delito_com = Código) %>%
  #filter(est_conyugal != -99) %>%
  #filter(zona_ocu_hecho != -99) %>%
  mutate(año_hecho = año_hecho - 2000) %>%
  filter(delito_com>= 227) %>%
  filter(delito_com<=231) %>%
  filter(sexo_agraviados != -99) %>%
  filter(edad_agrav != -99) %>%
  left_join(dicAgraviados23[dicAgraviados23$Valor == "DEPARTAMENTO DE OCURRENCIA DEL HECHO",], by = c("depto_ocu_hecho" ="Etiqueta")) %>%
  select(-depto_ocu_hecho, -Valor) %>%
  rename(depto_ocu_hecho = Código) 
  
  
# Ejecución apriori en datos completos
rAgraviados23 <- apriori(sdAgraviados23, parameter= list(support=0.2, confidence=0.5))

muestra23 <- as(rAgraviados23,"data.frame")
```

